"""Initial_migration_users_departments_students_faculty

Revision ID: 0b6efd9883bc
Revises: 
Create Date: 2026-08-15 13:10:00.867256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.base



# revision identifiers, used by Alembic.
revision: str = '0b6efd9883bc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('building', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departments_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_departments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_departments_name'), ['name'], unique=True)

    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'FACULTY', 'ADMIN', name='user_role_enum', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'DEACTIVATED', name='user_status_enum', native_enum=False), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_status'), ['status'], unique=False)

    op.create_table('faculty',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('user_id', app.models.base.GUID(), nullable=False),
    sa.Column('department_id', app.models.base.GUID(), nullable=False),
    sa.Column('employee_id_number', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('office_location', sa.String(length=100), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('meeting_mode', sa.Enum('IN_PERSON', 'VIRTUAL', 'HYBRID', name='meeting_mode_enum', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('faculty', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_faculty_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_faculty_employee_id_number'), ['employee_id_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_faculty_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_faculty_user_id'), ['user_id'], unique=True)

    op.create_table('students',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('user_id', app.models.base.GUID(), nullable=False),
    sa.Column('student_id_number', sa.String(length=50), nullable=False),
    sa.Column('major', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_student_id_number'), ['student_id_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_students_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_user_id'))
        batch_op.drop_index(batch_op.f('ix_students_student_id_number'))
        batch_op.drop_index(batch_op.f('ix_students_id'))

    op.drop_table('students')
    with op.batch_alter_table('faculty', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_faculty_user_id'))
        batch_op.drop_index(batch_op.f('ix_faculty_id'))
        batch_op.drop_index(batch_op.f('ix_faculty_employee_id_number'))
        batch_op.drop_index(batch_op.f('ix_faculty_department_id'))

    op.drop_table('faculty')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_status'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_name'))
        batch_op.drop_index(batch_op.f('ix_departments_id'))
        batch_op.drop_index(batch_op.f('ix_departments_code'))

    op.drop_table('departments')
    # ### end Alembic commands ###
