"""Add_availability_and_leave_models

Revision ID: 254a4c644b58
Revises: 0b6efd9883bc
Create Date: 2026-08-15 13:45:03.412867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.base



# revision identifiers, used by Alembic.
revision: str = '254a4c644b58'
down_revision: Union[str, Sequence[str], None] = '0b6efd9883bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocked_slots',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('faculty_id', app.models.base.GUID(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blocked_slots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blocked_slots_end_datetime'), ['end_datetime'], unique=False)
        batch_op.create_index(batch_op.f('ix_blocked_slots_faculty_id'), ['faculty_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blocked_slots_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blocked_slots_start_datetime'), ['start_datetime'], unique=False)

    op.create_table('leave_records',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('faculty_id', app.models.base.GUID(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('leave_type', sa.Enum('FULL_DAY', 'HALF_DAY_MORNING', 'HALF_DAY_AFTERNOON', 'MULTI_DAY', name='leave_type_enum', native_enum=False), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('APPROVED', 'CANCELLED', name='leave_status_enum', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leave_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leave_records_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_leave_records_faculty_id'), ['faculty_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leave_records_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leave_records_start_date'), ['start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_leave_records_status'), ['status'], unique=False)

    op.create_table('regular_availability',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('faculty_id', app.models.base.GUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('slot_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('regular_availability', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_regular_availability_day_of_week'), ['day_of_week'], unique=False)
        batch_op.create_index(batch_op.f('ix_regular_availability_faculty_id'), ['faculty_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_regular_availability_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_regular_availability_is_active'), ['is_active'], unique=False)

    op.create_table('temporary_availability',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('faculty_id', app.models.base.GUID(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('temporary_availability', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_temporary_availability_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_temporary_availability_faculty_id'), ['faculty_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_temporary_availability_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temporary_availability', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_temporary_availability_id'))
        batch_op.drop_index(batch_op.f('ix_temporary_availability_faculty_id'))
        batch_op.drop_index(batch_op.f('ix_temporary_availability_date'))

    op.drop_table('temporary_availability')
    with op.batch_alter_table('regular_availability', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_regular_availability_is_active'))
        batch_op.drop_index(batch_op.f('ix_regular_availability_id'))
        batch_op.drop_index(batch_op.f('ix_regular_availability_faculty_id'))
        batch_op.drop_index(batch_op.f('ix_regular_availability_day_of_week'))

    op.drop_table('regular_availability')
    with op.batch_alter_table('leave_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leave_records_status'))
        batch_op.drop_index(batch_op.f('ix_leave_records_start_date'))
        batch_op.drop_index(batch_op.f('ix_leave_records_id'))
        batch_op.drop_index(batch_op.f('ix_leave_records_faculty_id'))
        batch_op.drop_index(batch_op.f('ix_leave_records_end_date'))

    op.drop_table('leave_records')
    with op.batch_alter_table('blocked_slots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blocked_slots_start_datetime'))
        batch_op.drop_index(batch_op.f('ix_blocked_slots_id'))
        batch_op.drop_index(batch_op.f('ix_blocked_slots_faculty_id'))
        batch_op.drop_index(batch_op.f('ix_blocked_slots_end_datetime'))

    op.drop_table('blocked_slots')
    # ### end Alembic commands ###
