"""Add_appointment_model

Revision ID: 7f3ffbb07770
Revises: 254a4c644b58
Create Date: 2026-08-15 14:14:54.316063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.base



# revision identifiers, used by Alembic.
revision: str = '7f3ffbb07770'
down_revision: Union[str, Sequence[str], None] = '254a4c644b58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('student_id', app.models.base.GUID(), nullable=False),
    sa.Column('faculty_id', app.models.base.GUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'ACCEPTED', 'REJECTED', 'CANCELLED', 'COMPLETED', 'RESCHEDULE_PROPOSED', name='appointment_status_enum', native_enum=False), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('faculty_notes', sa.String(length=255), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointments_date'), ['date'], unique=False)
        batch_op.create_index('ix_appointments_faculty_date_status', ['faculty_id', 'date', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_faculty_id'), ['faculty_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_status'), ['status'], unique=False)
        batch_op.create_index('ix_appointments_student_date_status', ['student_id', 'date', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointments_student_id'))
        batch_op.drop_index('ix_appointments_student_date_status')
        batch_op.drop_index(batch_op.f('ix_appointments_status'))
        batch_op.drop_index(batch_op.f('ix_appointments_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_faculty_id'))
        batch_op.drop_index('ix_appointments_faculty_date_status')
        batch_op.drop_index(batch_op.f('ix_appointments_date'))

    op.drop_table('appointments')
    # ### end Alembic commands ###
