from app.schemas.common import MessageResponse, PaginatedResponse
from app.schemas.department import DepartmentBase, DepartmentCreate, DepartmentUpdate, DepartmentResponse
from app.schemas.student import StudentBase, StudentCreate, StudentUpdate, StudentResponse
from app.schemas.faculty import FacultyBase, FacultyCreate, FacultyUpdate, FacultyResponse, FacultyPublicProfile
from app.schemas.user import UserBase, UserCreate, UserUpdate, UserStatusUpdate, UserResponse, UserProfileResponse
from app.schemas.auth import LoginRequest, TokenResponse, RegisterStudentRequest, RegisterFacultyRequest
from app.schemas.availability import (
    RegularAvailabilityBase,
    RegularAvailabilityCreate,
    RegularAvailabilityUpdate,
    RegularAvailabilityResponse,
    TemporaryAvailabilityBase,
    TemporaryAvailabilityCreate,
    TemporaryAvailabilityResponse,
    BlockedSlotBase,
    BlockedSlotCreate,
    BlockedSlotUpdate,
    BlockedSlotResponse,
    TimeIntervalSchema,
    BookableSlotSchema,
    FacultyAvailabilityResponse,
    FacultyAvailabilityDetailResponse,
)
from app.schemas.leave import LeaveBase, LeaveCreate, LeaveUpdate, LeaveResponse
from app.schemas.appointment import (
    StudentSummary,
    FacultySummary,
    AppointmentCreate,
    AppointmentActionRequest,
    AppointmentResponse,
    AppointmentFilter,
)

__all__ = [
    "MessageResponse",
    "PaginatedResponse",
    "DepartmentBase",
    "DepartmentCreate",
    "DepartmentUpdate",
    "DepartmentResponse",
    "StudentBase",
    "StudentCreate",
    "StudentUpdate",
    "StudentResponse",
    "FacultyBase",
    "FacultyCreate",
    "FacultyUpdate",
    "FacultyResponse",
    "FacultyPublicProfile",
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserStatusUpdate",
    "UserResponse",
    "UserProfileResponse",
    "LoginRequest",
    "TokenResponse",
    "RegisterStudentRequest",
    "RegisterFacultyRequest",
    "RegularAvailabilityBase",
    "RegularAvailabilityCreate",
    "RegularAvailabilityUpdate",
    "RegularAvailabilityResponse",
    "TemporaryAvailabilityBase",
    "TemporaryAvailabilityCreate",
    "TemporaryAvailabilityResponse",
    "BlockedSlotBase",
    "BlockedSlotCreate",
    "BlockedSlotUpdate",
    "BlockedSlotResponse",
    "TimeIntervalSchema",
    "BookableSlotSchema",
    "FacultyAvailabilityResponse",
    "FacultyAvailabilityDetailResponse",
    "LeaveBase",
    "LeaveCreate",
    "LeaveUpdate",
    "LeaveResponse",
    "StudentSummary",
    "FacultySummary",
    "AppointmentCreate",
    "AppointmentActionRequest",
    "AppointmentResponse",
    "AppointmentFilter",
]
